### ISSUE TITLE
Suggestion:  Make aptli understand (or ignore) standard common apt flags and switches

### ISSUE THREAD

**Issue by the-moog** [eliphatfs/apt-local-install#1]
That way existing scripts will not fail, e.g. apt install -y xyz

**Comment by eliphatfs** [comment]
I haven't thought of making aptli a drop-in replacement for apt, but I think it would be a good idea.

**Comment by the-moog** [comment]
I think apt itself is very large so a complete drop in would be a lot of work and probably unnecessary, but being able to make temporary local non unprivilaged installs from apt with no more than an alias to it's runtime would be very useful.
Also great for security or remote updates too. You have probbaly heard lots about various online repos being poluted by malicious code commits, being able to evaluate  the remote source in a chroot would be great for PPAs.

**Comment by eliphatfs** [comment]
Added a dummy `-y`. Closing the issue for now. I will appreciate it very much if you could provide a list of these common flags.
