### ISSUE TITLE
Fails to meet a common use case by needing a re-login.

### ISSUE THREAD

**Issue by the-moog** [eliphatfs/apt-local-install#2]
A common use case for such a tool would be to allow compilation of builds to pass where dependencies need to be installed with sudo (and docker is not available).

However the requirement to close and open a new shell trashes that as that would break a running script.

Suggesion: Something like source the .bashrc into the current shell environment

**Comment by eliphatfs** [comment]
After digging up a bit I think there is currently no way to control the parent shell from a child process. I would suggest adding `source ~/.bashrc` manually where you set up. That is, when you setup aliases in this case, you add two more lines -- run `./aptli` to set it up and then `source ~/.bashrc`.

**Comment by the-moog** [comment]
I've not tried it, (I may when I get a chance) but I think you can just subprocess(["/bin/bash", "-l"], shell=True) being careful to not close stdin as that would close the process. Or (simper and what is probably a wrapper for just that), the pypy package pexpect https://pypi.org/project/pexpect/  .
Thus you create a non-terminating login shell (bash -l) then use that shell to re-load the running script by passing it's location to finish the apt install job.
You could even use multiprocessing to allow the two instances of the same script to communicate and perform their tasks.

**Comment by eliphatfs** [comment]
Then I am essentially creating a shell instance myself, which is kind of weird to add inside the package manager compared with being an external utility. But if I were to code up an external utility, why not just `source ~/.bashrc`?
Also, I don't think interactive shells started by a script work well in CI/CD. CI/CD does not work by dumping commands into stdin; they have their own mechanisms of running commands.

**Comment by eliphatfs** [comment]
Added `source ~/.bashrc` instructions in README. Closing for now. If you have more comments or suggestions feel free to open another issue.
